### ISSUE TITLE
Figure out how to enforce that observed element is a descendant of the viewport element

### ISSUE THREAD

**Issue by ojanvafai** [slightlyoff/IntersectionObserver#16] opened 2015-08-15 02:11 UTC
We should throw (or silently fail) if you call observe on an element that is not a descendant of the viewport element. Similarly, we need to handle when an observed element moves to a different subtree.

**Comment by esprehn** [comment] 2015-09-08 22:27
Discussed with @ojanvafai 

1) Calling observe() when root is not your ancestor throws.
2) If at any point you're removed from under the root, it's as if you called unobserve().

This provides pretty decent fallback and edge case behavior.

The only catch is an infinite list that removes and re-adds elements will need to call observe() after inserting new items, but one that uses transform to move elements around would not. This seems fine, the rule is "Any new things inserted under root always need observe()."

**Comment by szager-chromium** [comment] 2015-11-20 21:28
Duplicate of #58

**Closed by szager-chromium** 2015-11-20 21:28 UTC
Labels: duplicate, needs spec
