### ISSUE TITLE
viewport rect should be the intersection of ancestor scrollers

### ISSUE THREAD

**Issue by ojanvafai** [slightlyoff/IntersectionObserver#22] opened 2015-08-27 12:38 UTC
At the CSS F2F, there was clear agreement that this is a common enough non-malicious case that the viewport rect should be the intersection of all the ancestor clipping due to overflow (hidden, auto, scroll).

To be clear, this should only apply if the viewport parameter is null, right?

@esprehn

**Comment by slightlyoff** [comment] 2015-09-08 21:55
Agreed that this should only happen when root (nee "viewport") parameter is null.

**Comment by ojanvafai** [comment] 2015-09-08 22:04
Actually, it should include all the clips from the observed element to the root.

**Comment by szager-chromium** [comment] 2015-11-20 21:29
Duplicate of #62

**Closed by szager-chromium** 2015-11-20 21:29 UTC
Labels: duplicate, needs spec
