### ISSUE TITLE
Make sure that time basis and types are lined up with Frame Timing

### ISSUE THREAD

**Issue by slightlyoff** [slightlyoff/IntersectionObserver#59] opened 2015-10-26 07:21 UTC
From the TPAC WebPerf discussion, we should make sure that record delivery uses the same time type and time basis as Frame Timing so we can correlate.

**Comment by ojanvafai** [comment] 2015-10-30 06:16
@tabatkins tells me to use http://www.w3.org/TR/hr-time/#sec-DOMHighResTimeStamp. So, we want some text like "The DOMHighResTimeStamp type is used to store a time value measured relative to the navigationStart attribute of the PerformanceTiming interface [NavigationTiming], the start of navigation of the document, or a time value that represents a duration between two DOMHighResTimeStamps."

@bzbarsky does that address the concern you had?

@mpb @szager-chromium

**Comment by ojanvafai** [comment] 2015-10-30 06:18
This is a dupe of issue 51. Will move this comment there.

**Closed by ojanvafai** 2015-10-30 06:18 UTC
